//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektSemestralny
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// Class <c>Gry</c> contains values of 'Gry' table
    /// </summary>
    public partial class Gry
    {
        /// <summary>
        /// Constructs a new <see cref="Gry"/> instance.
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gry()
        {
            this.Wypozyczenias = new HashSet<Wypozyczenia>();
        }

        /// <value>Gets the value of ID_gry</value>
        public int ID_gry { get; set; }
        /// <value>Gets the value of Nazwa</value>
        public string Nazwa { get; set; }
        /// <value>Gets the value of Kategoria</value>
        public string Kategoria { get; set; }
        /// <value>Gets the value of Kategoria_wiekowa</value>
        public string Kategoria_wiekowa { get; set; }
        /// <value>Gets the value of Data_wydania</value>
        public string Data_wydania { get; set; }
        /// <value>Gets the value of Cena_dzien</value>
        public int Cena_dzien { get; set; }

        /// <summary>
        /// Contains all values of columns in <c>Wypozyczenia</c> table
        /// <list type="table">
        /// <item>
        /// <term>ID_wypozyczenia</term>
        /// <description>ID_wypozyczenia column</description>
        /// </item>
        /// <item>
        /// <term>ID_Gry</term>
        /// <description>ID_Gry column</description>
        /// </item>
        /// <item>
        /// <term>ID_pracownika</term>
        /// <description>ID_pracownika column</description>
        /// </item>
        /// <item>
        /// <term>ID_klienta</term>
        /// <description>ID_klienta column</description>
        /// </item>
        /// <item>
        /// <term>Data_wypozyczenia</term>
        /// <description>Data_wypozyczenia column</description>
        /// </item>
        /// </list>
        /// </summary>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Wypozyczenia> Wypozyczenias { get; set; }
    }
}
