//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektSemestralny
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    /// <summary>
    /// The <c>Wypozyczalnia_Gier_komputerowychEntities</c> class
    /// </summary>
    public partial class Wypozyczalnia_Gier_komputerowychEntities : DbContext
    {
        /// <summary>
        /// Constructs a new <see cref="Wypozyczalnia_Gier_komputerowychEntities"/> instance.
        /// </summary>
        public Wypozyczalnia_Gier_komputerowychEntities()
            : base("name=Wypozyczalnia_Gier_komputerowychEntities")
        {
        }
        /// <summary>
        /// The <c>OnModelCreating</c>c> method
        /// </summary>
        /// <param name="modelBuilder"></param>
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        /// <summary>
        /// <value>Gets <c>Gry</c> properties</value>
        /// </summary>
        public virtual DbSet<Gry> Gries { get; set; }
        /// <summary>
        /// <value>Gets<c>Klienci</c> properties</value>
        /// </summary>
        public virtual DbSet<Klienci> Kliencis { get; set; }
        /// <summary>
        /// <value>Gets <c>Pracownicy</c> properties</value>
        /// </summary>
        public virtual DbSet<Pracownicy> Pracownicies { get; set; }
        /// <summary>
        /// <value>Gets <c>Wypozyczenia</c> properties</value>
        /// </summary>
        public virtual DbSet<Wypozyczenia> Wypozyczenias { get; set; }
        /// <summary>
        /// <value>Gets <c>Zwroty</c> properties</value>
        /// </summary>
        public virtual DbSet<Zwroty> Zwroties { get; set; }
    }
}
